# Generated by Django 4.1.7 on 2024-02-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=120)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio Social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto Terminal'), ('EV', 'Estancia de Verano'), ('TC', 'Trayectoria Curricular'), ('EG', 'Eleccion de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('OTRO', 'Otro')], default='SS', max_length=4, verbose_name='SS')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ACE', 'Aceptada'), ('REJ', 'Rechazada'), ('PEN', 'Pendiente')], default='PEN', max_length=4, verbose_name='PEN')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
