# Generated by Django 4.1.7 on 2024-02-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tutorias', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tutor'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tutor'),
        ),
    ]
