# Generated by Django 4.1.7 on 2024-02-28 11:42

import Usuarios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(max_length=11, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=Usuarios.models.usr_pfp_path)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('correo_personal', models.EmailField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(choices=[('TUT', 'Tutor'), ('COR', 'Coordinador'), ('ALU', 'Alumno'), ('COD', 'Coda')], default='USR', max_length=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', Usuarios.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coda',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cubiculo', models.IntegerField()),
                ('horario', models.FileField(blank=True, null=True, upload_to='')),
                ('coordinacion', models.CharField(choices=[('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30)),
                ('es_coordinador', models.BooleanField(default=False)),
                ('tema_tutorias', models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio Social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto Terminal'), ('EV', 'Estancia de Verano'), ('TC', 'Trayectoria Curricular'), ('EG', 'Eleccion de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('OTRO', 'Otro')], default='OTRO', max_length=4)),
            ],
            options={
                'verbose_name': 'CODA',
                'verbose_name_plural': 'CODAA',
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', Usuarios.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cordinador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cubiculo', models.IntegerField()),
                ('horario', models.FileField(blank=True, null=True, upload_to='')),
                ('coordinacion', models.CharField(choices=[('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30)),
                ('es_coordinador', models.BooleanField(default=True)),
                ('tutor_tutorias', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cordinador',
                'verbose_name_plural': 'Cordinadores',
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', Usuarios.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cubiculo', models.IntegerField()),
                ('horario', models.FileField(blank=True, null=True, upload_to='')),
                ('coordinacion', models.CharField(choices=[('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30)),
                ('es_coordinador', models.BooleanField(default=False)),
                ('tema_tutorias', models.CharField(choices=[('BEC', 'Becas'), ('INS', 'Inscripción'), ('ING', 'Inglés'), ('ORG', 'Órgano colegiado'), ('REG', 'Reglamentos'), ('SS', 'Servicio Social'), ('MOV', 'Movilidad'), ('PT', 'Proyecto Terminal'), ('EV', 'Estancia de Verano'), ('TC', 'Trayectoria Curricular'), ('EG', 'Eleccion de grupo'), ('TIT', 'Titulación'), ('EGRE', 'Egreso'), ('PER', 'Personales'), ('SR', 'Seguimiento de reunión'), ('OTRO', 'Otro')], default='OTRO', max_length=4)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', Usuarios.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.CharField(choices=[('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30)),
                ('trayectoria', models.FileField(blank=True, null=True, upload_to=Usuarios.models.alumno_trayectoria_path)),
                ('tutor_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuarios.tutor')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
            bases=('Usuarios.usuario',),
            managers=[
                ('objects', Usuarios.models.UserManager()),
            ],
        ),
    ]
