# Generated by Django 4.1.13 on 2024-02-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('', 'Seleccione Carrera'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='coda',
            name='coordinacion',
            field=models.CharField(choices=[('', 'Seleccione Carrera'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cordinador',
            name='coordinacion',
            field=models.CharField(choices=[('', 'Seleccione Carrera'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='coordinacion',
            field=models.CharField(choices=[('', 'Seleccione Carrera'), ('MAT', 'Matemáticas Aplicadas'), ('COM', 'Ingeniería en Computación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('', 'Seleccione Rol'), ('TUT', 'Tutor'), ('COR', 'Coordinador'), ('ALU', 'Alumno'), ('CODA', 'Coda')], default='USR', max_length=8),
        ),
    ]
